Minor spelling fixes

diff --git a/bin/asahi-encrypt b/bin/asahi-encrypt
--- a/bin/asahi-encrypt
+++ b/bin/asahi-encrypt
@@ -7,7 +7,6 @@ msg() { echo ">>> $1"; }
 CHROOT=/mnt
 LUKS_HDR_BYTES=$[ 32*1024*1024 ]
 USAGE_SHORT="Usage: ${0##*/} /dev/nvme0n1p{N} [OPTIONS]"
-CUR_ROOT=`findmnt -nvo SOURCE -M /` || die
 ERR_LOG=/tmp/${0##*/}-$$.log
 unset action_{mount,encrypt,umount} ARGS raw_dev dev size type uuid luks_name
 
@@ -18,23 +17,23 @@ while (( $# )); do
 $USAGE_SHORT
        ${0##*/} -l [/dev/nvme0n1]
 
-  Where /dev/nvme0n1p{N} is the root partition of Asahi linux
+  Where /dev/nvme0n1p{N} is the root partition of Asahi Linux
 installation. The installation is expected to consist of four
 partitions:
-    /dev/nvme0n1p{N-3} - 2.5G apfs  Macos Boot Loader
+    /dev/nvme0n1p{N-3} - 2.5G apfs  macOS Boot Loader
     /dev/nvme0n1p{N-2} - 500M vfat  EFI
     /dev/nvme0n1p{N-1} - 1.0G ext4  Boot
-    /dev/nvme0n1p{N}   -      btrfs Root (will be encrypted)
+    /dev/nvme0n1p{N}   -      btrfs Root (to be encrypted)
 
-  You can easily determine suitable root partitions using
-one of the commands: '${0##*/} -l' or 'lsblk -f'.
+  Determine suitable partitions with: '${0##*/} -l'.
+Alternatively get detailed partition list with: 'lsblk -f'.
 Unencrypted root partitions of a typical Fedora Linux
 installation are usually labeled 'fedora'.
 
 OPTIONS:
-    -m  - Just mount target system on /mnt
-    -e  - Just encrypt target system, implies '-m'
-    -u  - Just unmount target system from /mnt
+    -m  - Mount target system on /mnt
+    -e  - Encrypt target system, implies '-m'
+    -u  - Unmount target system from /mnt
     -l  - List suitable root partitions and exit
     -h  - Display this help
 
@@ -75,7 +74,7 @@ chroot_mount() {
             # Unmounting each partition/volume if it is mounted not to desired path
             while read root mp; do
                 [[ $root == /$vol ]] || continue
-                [[ $mp != $target ]] || die "Inplace encryptiopn of a running system is not allowed!"
+                [[ $mp != $target ]] || die "In-place encryption of a running system is not allowed"
                 [[ $mp == $CHROOT$target ]] && continue 2 || sudo umount "$mp" || die
             done <<<"`findmnt -no FSROOT,TARGET "${dev[n]}"`"
             # Mounting each partition/volume to desired path
@@ -126,7 +125,7 @@ chroot_umount() {
 
 encrypt_root() {
     trap 'rm "$ERR_LOG"' EXIT
-    # Encrypting the root partition inplace
+    # Encrypting the root partition in place
     if  ! sudo cryptsetup reencrypt --encrypt --reduce-device-size "$LUKS_HDR_BYTES" "${raw_dev[R]}" > >(tee "$ERR_LOG") 2>&1; then
         # When --try_repair is given, check if command failed due to a repair requirement and try to fix
         if  [[ $1 == --try_repair ]] && grep -qiE "requires reencryption recovery|run repair first" "$ERR_LOG"; then
@@ -181,7 +180,7 @@ check_installation() {
     local R=$1 non_fatal=$2 e n
     local exp_type=( "apfs" "vfat" "ext4" "btrfs|crypto_LUKS" )
     [[ ${dev[R]} != $CUR_ROOT ]] || { [[ $non_fatal ]] && return 1; } \
-        || die "Inplace encryptiopn of a running system is not allowed!"
+        || die "In-place encryption of a running system is not allowed"
     # Checking if root partition and 3 preceeding partitions have expected filesystem types
     for (( e = 0; e < 4; e++ )); do
         (( n = R - 3 + e ))
@@ -217,7 +216,7 @@ asahi_encrypter() {
                 || die "Failed to resize the root partition: ${raw_dev[R]}"
         fi
         chroot_umount
-        msg "Encrypting the target root partition inplace"
+        msg "Encrypting the target root partition in place"
         encrypt_root
     fi
     if  [[ $action_encrypt || $action_mount ]]; then
@@ -252,13 +251,13 @@ asahi_encrypter() {
         sudo chroot "$CHROOT" grub2-mkconfig -o "$grub_cfg" && \
         sudo chroot "$CHROOT" dracut -f --kver "$kver" \
             || die "Failed to rebuild initramfs"
-        msg "Disabling selinux enforcing for the target system until next boot"
+        msg "Disabling SELinux enforcing for the target system until next boot"
         sudo chroot "$CHROOT" grubby --update-kernel ALL --args enforcing=0 \
-            || die "Failed to temporarily disable selinux enforcement for the target system"
-        # Scheduling regeneration of initrd and reenabling selinux enforcing on next boot
+            || die "Failed to temporarily disable SELinux enforcement for the target system"
+        # Scheduling regeneration of initrd and reenabling SELinux enforcing on next boot
         sudo tee "$CHROOT"/etc/cron.d/post_encrypt_update >/dev/null \
             <<< "@reboot root grub2-mkconfig -o $grub_cfg && dracut -f && setenforce 1 && rm /etc/cron.d/post_encrypt_update" \
-            || die "Unable to schedule enabling of selinux enforcing on the next boot for target system"
+            || die "Unable to schedule enabling of SELinux enforcing on the next boot for target system"
     fi
     if  [[ $action_umount ]]; then
         chroot_umount
@@ -286,6 +285,7 @@ asahi_finder() {
     || die "$USAGE_SHORT\nUse '-h' for help"
 (( ${#ARGS[@]} <= 1 )) \
     || die "Extra arguments passed: ${ARGS[*]:1}"
+CUR_ROOT=`findmnt -nvo SOURCE -M /` || die
 
 # Performing the actions
 if  (( action_list )); then
@@ -294,7 +294,7 @@ if  (( action_list )); then
 else
     [[   $R  ]] || die "Only partitions are allowed for encryption, not a whole device: ${ARGS[0]}"
     (( R > 3 )) || die "The partition number should be greater than 4: ${ARGS[0]}"
-    # S, E, B, R - numbers of corresponfing Stub-MacOS, EFI, Boot and Root partitions in the installation layout
+    # S, E, B, R - numbers of corresponding Stub-MacOS, EFI, Boot and Root partitions in the installation layout
     (( S=R-3, E=R-2, B=R-1 ))
     (( action_mount || action_encrypt || action_umount )) || action_mount=1 action_encrypt=1 action_umount=1
     asahi_encrypter
