feat: add encryption resume/repair, 'setenforce 1' on reboot; improve messages; add partprobe/sleep after encryption

diff --git a/bin/asahi-encrypt b/bin/asahi-encrypt
--- a/bin/asahi-encrypt
+++ b/bin/asahi-encrypt
@@ -8,9 +8,10 @@ CHROOT=/mnt
 LUKS_HDR_BYTES=$[ 32*1024*1024 ]
 USAGE_SHORT="Usage: ${0##*/} /dev/nvme0n1p{N} [OPTIONS]"
 CUR_ROOT=`findmnt -nvo SOURCE -M /` || die
+ERR_LOG=/tmp/${0##*/}-$$.log
 unset action_{mount,encrypt,umount} ARGS raw_dev dev size type uuid luks_name
 
-# Parsing command line
+# Parsing the command line
 while (( $# )); do
     case $1 in
         -h) cat <<-EOF
@@ -53,25 +54,20 @@ EOF
     shift
 done
 
-# Checking arguments & initializing variables
-[[ ${#ARGS[@]} == 0 && $action_list || ${ARGS[0]} =~ ^(/dev/nvme[0-9]+n[0-9]+)(p([0-9]+))?$ ]] \
-    && base=${BASH_REMATCH[1]:-/dev/nvme0n1} R=${BASH_REMATCH[3]} \
-    || die "$USAGE_SHORT\nUse '-h' for help"
-(( ${#ARGS[@]} <= 1 )) \
-    || die "Extra arguments passed: ${ARGS[*]:1}"
 
 is_encrypted() { [[ ${type[R]} == crypto_LUKS ]]; }
 is_open() { [[ -b /dev/mapper/${luks_name[R]} ]]; }
 
+mount_msg() { (( msg_shown )) || msg "Mounting the target system on $CHROOT"; msg_shown=1; }
 chroot_mount() {
     local targets=( [R]="root: home:/home" [B]=":/boot" [E]=":/boot/efi" )
     if  is_encrypted && ! is_open; then
-        msg "Opening encrypted root partition"
+        msg "Opening the encrypted root partition of the target system"
         sudo cryptsetup open "${raw_dev[R]}" "${luks_name[R]}" || die "Failed to open LUKS partition: ${raw_dev[R]}"
+        # Just indicating that the device is open, instead of calling read_partitions
         dev[R]=/dev/mapper/${luks_name[R]}
     fi
-    msg "Mounting filesystems on $CHROOT"
-    local n m spec vol target root mp fstype opts fstab=$CHROOT/etc/fstab ok
+    local msg_shown n m spec vol target root mp fstype opts fstab=$CHROOT/etc/fstab ok
     for n in $R $B $E; do
         # If partition has subvolumes, handle each subvolume
         for spec in ${targets[n]}; do
@@ -83,7 +79,7 @@ chroot_mount() {
                 [[ $mp == $CHROOT$target ]] && continue 2 || sudo umount "$mp" || die
             done <<<"`findmnt -no FSROOT,TARGET "${dev[n]}"`"
             # Mounting each partition/volume to desired path
-            sudo mount ${vol:+-o subvol=$vol} "${dev[n]}" "$CHROOT$target" || die
+            mount_msg && sudo mount ${vol:+-o subvol=$vol} "${dev[n]}" "$CHROOT$target" || die
         done
         (( n == R )) || continue
         # Checking that the Boot and EFI partitions, selected by layout correspond to the fstab on the target system
@@ -99,7 +95,9 @@ chroot_mount() {
     if  [[ $1 == --vfs ]]; then
         # Mounting virtual filesystems
         while read mp fstype opts; do
-            mountpoint -q "$CHROOT/$mp" || sudo mount -t "$fstype" -o "$opts" none "$CHROOT/$mp" || die
+            if ! mountpoint -q "$CHROOT/$mp"; then
+                mount_msg && sudo mount -t "$fstype" -o "$opts" none "$CHROOT/$mp" || die
+            fi
         done << EOF
 proc proc nosuid,noexec,nodev
 sys sysfs nosuid,noexec,nodev,ro
@@ -114,12 +112,44 @@ EOF
 }
 
 chroot_umount() {
-    msg "Unmounting filesystems from $CHROOT"
-    ! mountpoint -q "$CHROOT" || sudo umount -R "$CHROOT" \
-        || die "Failed to recursively unmount directory: $CHROOT"
+    if  mountpoint -q "$CHROOT"; then
+        msg "Unmounting the target system from $CHROOT"
+        sudo umount -R "$CHROOT" || die "Failed to recursively unmount directory: $CHROOT"
+    fi
     # Check if target partitions are mounted somewhere else
     local mps=( `xargs -n1 findmnt -no TARGET <<<"${dev[E]} ${dev[B]} ${dev[R]}" | sort -r` )
-    [[ ! $mps ]] || sudo umount $mps || die "Failed to unmount some partitions"
+    if  [[ $mps ]]; then
+        msg "Unmounting the EFI, boot and root partitions of the target system"
+        sudo umount $mps || die "Failed to unmount some partitions"
+    fi
+}
+
+encrypt_root() {
+    trap 'rm "$ERR_LOG"' EXIT
+    # Encrypting the root partition inplace
+    if  ! sudo cryptsetup reencrypt --encrypt --reduce-device-size "$LUKS_HDR_BYTES" "${raw_dev[R]}" > >(tee "$ERR_LOG") 2>&1; then
+        # When --try_repair is given, check if command failed due to a repair requirement and try to fix
+        if  [[ $1 == --try_repair ]] && grep -qiE "requires reencryption recovery|run repair first" "$ERR_LOG"; then
+            local backup
+            printf -v backup "./luks-header-${uuid[R]}.%(%F_%H%M%S)T.backup" -1
+            msg "Backing up LUKS header of the target root partition to: $backup"
+            sudo cryptsetup luksHeaderBackup --header-backup-file "$backup" "${raw_dev[R]}" \
+                || die "Failed to backup LUKS header"
+            msg "Repairing the target root partition"
+            sudo cryptsetup repair "${raw_dev[R]}" \
+                || die "Failed to repair target root partition"
+            msg "Resuming encryption of the repaired target root partition"
+            encrypt_root
+            return
+        else
+            die "Failed to encrypt root partition"
+        fi
+    fi
+    # Just in case...
+    sleep 2
+    sudo partprobe "$base"
+    # Updating partition information after encryption since UUID and type has changed.
+    read_partitions
 }
 
 read_partitions() {
@@ -182,19 +212,25 @@ asahi_encrypter() {
         fs_size=`lsblk -ndbo FSSIZE "${raw_dev[R]}"`
         (( fs_size )) || die "Can't determine filesystem size of the root partition: ${raw_dev[R]}"
         if  (( size[R] - fs_size < LUKS_HDR_BYTES )); then
-            msg "Shrinking root FS to accomodate LUKS header"
-            sudo btrfs filesystem resize $[size[R] - LUKS_HDR_BYTES] "$CHROOT" || die "Failed to resize root partition: ${raw_dev[R]}"
+            msg "Shrinking the target root filesystem to accomodate LUKS header"
+            sudo btrfs filesystem resize $[size[R] - LUKS_HDR_BYTES] "$CHROOT" \
+                || die "Failed to resize the root partition: ${raw_dev[R]}"
         fi
         chroot_umount
-        msg "Encrypting root partition inplace"
-        sudo cryptsetup reencrypt --encrypt --reduce-device-size "$LUKS_HDR_BYTES" "${raw_dev[R]}" || die "Failed to encrypt root partition"
-        type[R]=crypto_LUKS
+        msg "Encrypting the target root partition inplace"
+        encrypt_root
     fi
     if  [[ $action_encrypt || $action_mount ]]; then
+        # Checking if the encryption was interrupted
+        if  grep -q "^Requirements:.*\bonline-reencrypt" <<<"`sudo cryptsetup luksDump "${dev[R]}" 2>/dev/null`"; then
+            chroot_umount
+            msg "Resuming interrupted encryption of the target root partition"
+            encrypt_root --try_repair
+        fi
         chroot_mount --vfs
     fi
     if  [[ $action_encrypt ]]; then
-        msg "Configuring encrypted system"
+        msg "Configuring the target system"
         check_requirements
         crypttab=$CHROOT/etc/crypttab
         grubconf=$CHROOT/etc/default/grub
@@ -207,25 +243,27 @@ asahi_encrypter() {
         # Adding LUKS UUID to grub config
         sudo sed -ri "/^GRUB_CMDLINE_LINUX_DEFAULT=/{s/ rd.luks.uuid=[0-9a-f-]+//;s/=\"([^\"]*)\"/=\"\1 rd.luks.uuid=${uuid[R]}\"/}" "$grubconf" \
             || die "Failed to configure GRUB"
-        msg "Regenerating initrd"
+        msg "Rebuilding initramfs for the target system"
+        # Determining the latest installed kernel version
         for kver in "$CHROOT"/boot/vmlinuz-*; do
             kver=${kver#$CHROOT/boot/vmlinuz-}
         done
+        [[ $kver ]] || die "Failed to determine latest kernel version of target system"
         sudo chroot "$CHROOT" grub2-mkconfig -o "$grub_cfg" && \
         sudo chroot "$CHROOT" dracut -f --kver "$kver" \
-            || die "Failed to generate initrd"
-        msg "Disabling selinux enforcing for encrypted system until next boot"
+            || die "Failed to rebuild initramfs"
+        msg "Disabling selinux enforcing for the target system until next boot"
         sudo chroot "$CHROOT" grubby --update-kernel ALL --args enforcing=0 \
-            || die "Failed to temporarily disable selinux enforcement for encrypted system"
+            || die "Failed to temporarily disable selinux enforcement for the target system"
         # Scheduling regeneration of initrd and reenabling selinux enforcing on next boot
         sudo tee "$CHROOT"/etc/cron.d/post_encrypt_update >/dev/null \
-            <<< "@reboot root grub2-mkconfig -o $grub_cfg && dracut -f && rm /etc/cron.d/post_encrypt_update" \
-            || die "Unable to schedule enabling of selinux enforcing on the next boot for encrypted system"
+            <<< "@reboot root grub2-mkconfig -o $grub_cfg && dracut -f && setenforce 1 && rm /etc/cron.d/post_encrypt_update" \
+            || die "Unable to schedule enabling of selinux enforcing on the next boot for target system"
     fi
     if  [[ $action_umount ]]; then
         chroot_umount
         if  is_encrypted && is_open; then
-            msg "Closing encrypted root partition"
+            msg "Closing the encrypted root partition of the target system"
             sudo cryptsetup close "${luks_name[R]}" || die
         fi
     fi
@@ -241,15 +279,23 @@ asahi_finder() {
     [[ ! $matched ]] || lsblk -ndo PATH,FSTYPE,SIZE,LABEL "${matched[@]}"
 }
 
+
+# Checking arguments & initializing variables
+[[ ${#ARGS[@]} == 0 && $action_list || ${ARGS[0]} =~ ^(/dev/nvme[0-9]+n[0-9]+)(p([0-9]+))?$ ]] \
+    && base=${BASH_REMATCH[1]:-/dev/nvme0n1} R=${BASH_REMATCH[3]} \
+    || die "$USAGE_SHORT\nUse '-h' for help"
+(( ${#ARGS[@]} <= 1 )) \
+    || die "Extra arguments passed: ${ARGS[*]:1}"
+
+# Performing the actions
 if  (( action_list )); then
     [[ ! $R  ]] || die "Only whole device is allowed with option '-l', not a partition: ${ARGS[0]}"
     asahi_finder
 else
     [[   $R  ]] || die "Only partitions ars allowed for enctiption, not a whole device: ${ARGS[0]}"
-    (( R > 3 )) || die "Partition number should be greater than 4: ${ARGS[0]}"
-    # S, E, B, R - numbers of Stub-MacOS, EFI, Boot and Root partitions respectively
+    (( R > 3 )) || die "The partition number should be greater than 4: ${ARGS[0]}"
+    # S, E, B, R - numbers of corresponfing Stub-MacOS, EFI, Boot and Root partitions in the installation layout
     (( S=R-3, E=R-2, B=R-1 ))
     (( action_mount || action_encrypt || action_umount )) || action_mount=1 action_encrypt=1 action_umount=1
     asahi_encrypter
 fi
-
